### ISSUE TITLE
[Question]: Class "Captcha" not found

### ISSUE THREAD

**Issue by aeq-dev** [dominion-solutions/filament-captcha#3]
### What happened?

Just installed the package, import the component field, an error appears : 
`Class "Captcha" not found`

### How to reproduce the bug

Just installed the package, import the component field, an error appears : 
`Class "Captcha" not found`

### Package Version

Initial Release

### PHP Version

8.2

### Laravel Version

10

**Comment by aeq-dev** [comment]
Sorry for the delay,
And yes you're right, that's the missing thing, thanks.
Please, I want to display it in a blade view, (not filament views), let's say on landing contact page, how could I set it ? 
thanks

**Comment by spam-n-eggs** [comment]
Hi @aeq-dev.  

We would not recommend using this tool that way, however if you would like to do that it _is_ a component that could be imported.  Speaking strictly theoretically, you could try to register it as a service provider in your `app.php` and try to use it like a blade component `<x-...>.` You would have to re-create all of the filament "stuff" with a `FormRequest`

https://laravel.com/docs/10.x/blade#rendering-components Could help you on your journey.

Your Mileage May Vary.  Please [drop us a line](mailto:sales@dominion.solutions) if you do manage to get it working.
